package dev.parhamziaei.teahub.component;

import dev.parhamziaei.teahub.configuration.properties.InitializeProperties;
import dev.parhamziaei.teahub.dto.request.shop.admin.CategoryAdminRequest;
import dev.parhamziaei.teahub.dto.request.shop.admin.TeaSpeakProductInitRequest;
import dev.parhamziaei.teahub.entity.jpa.ApplicationSettings;
import dev.parhamziaei.teahub.entity.jpa.user.Role;
import dev.parhamziaei.teahub.entity.jpa.user.User;
import dev.parhamziaei.teahub.entity.jpa.user.UserSetting;
import dev.parhamziaei.teahub.entity.jpa.user.Wallet;
import dev.parhamziaei.teahub.enums.shop.ProductPeriod;
import dev.parhamziaei.teahub.enums.shop.ResourceType;
import dev.parhamziaei.teahub.enums.user.Roles;
import dev.parhamziaei.teahub.exception.custom.authorization.NoSuchRoleException;
import dev.parhamziaei.teahub.exception.custom.global.NoSuchDataException;
import dev.parhamziaei.teahub.repository.jpa.*;
import dev.parhamziaei.teahub.service.CategoryService;
import dev.parhamziaei.teahub.service.interfaces.ProductService;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

@Slf4j
@Component
@RequiredArgsConstructor
public class Initialization implements CommandLineRunner {

    private final InitializeProperties initProperties;
    private final UserRepository userRepository;
    private final RoleRepository roleRepository;
    private final CategoryService categoryService;
    private final ApplicationSettingRepository applicationSettingRepository;
    private final ProductService productService;
    private final TeaSpeakResourceRepository teaSpeakResourceRepository;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        try {
            categoryService.getAllCategories();
        } catch (NoSuchDataException ignored) {
            initTestCategory();
        }
        try {
            productService.getAllProducts();
        } catch (NoSuchDataException ignored) {
            initTestProduct();
        }
//        ipPanelService.sendTwoFactorSMS("0000", PhoneNumbers.formatedOf(initProperties.adminPhoneNumber()));
        initApplicationSetting();
        log.info("Initialization-Operation -> Application settings initialized");
        initRoles();
        if (!userRepository.existsByPhoneNumber(initProperties.adminPhoneNumber()))
            initAdmin();
    }

    public void initTestCategory() {
        CategoryAdminRequest adminRequest = new CategoryAdminRequest();
        adminRequest.setName("Test Category");
        adminRequest.setDescription("Test Category generated by system");
        adminRequest.setSlug("test");
        adminRequest.setActive(true);
        categoryService.addCategory(adminRequest);
        log.info("Initialization-Operation -> Test Category initialized");
    }

    public void initTestProduct() {
        TeaSpeakProductInitRequest initRequest = new TeaSpeakProductInitRequest();
        initRequest.setPrice(BigDecimal.valueOf(50000));
        initRequest.setProductPeriod(ProductPeriod.DAILY);
        initRequest.setMaxClients(32);
        initRequest.setEnabled(true);
        initRequest.setProductName("Test TeaSpeak Product");
        initRequest.setCategoryId(1L);
        initRequest.setType(ResourceType.TEASPEAK);
        productService.addProduct(initRequest);
        log.info("Initialization-Operation -> Test Product initialized");
    }

    public void initApplicationSetting() {
        if (applicationSettingRepository.findAll().isEmpty())
            applicationSettingRepository.save(new ApplicationSettings());
    }

    public void initRoles() {
        List<String> dbRoles = roleRepository.findAll().stream().map(Role::getName).toList();
        List<Roles> internalRoles = Arrays.stream(Roles.values()).toList();
        internalRoles.forEach(role -> {
            if (!dbRoles.contains(role.value())) {
                roleRepository.save(new Role(role.value(), role.hierarchy()));
                log.info("Initialization-Operation -> Role ({}) created by system", role.value());
            }
        });
    }

    private void initAdmin() {
        Role adminRole = roleRepository.findByName(Roles.ROLE_ADMIN.value())
                .orElseThrow(() -> new NoSuchRoleException(Roles.ROLE_ADMIN.value()));
        UserSetting userSetting = new UserSetting();
        User adminUser = User.builder()
                .email(initProperties.adminEmail())
                .phone(initProperties.adminPhoneNumber())
                .firstName(initProperties.adminFirstName())
                .lastName(initProperties.adminLastName())
                .emailVerified(true)
                .build();

        adminUser.setRole(adminRole);
        adminUser.setWallet(new Wallet());
        adminUser.setSetting(userSetting);
        userRepository.save(adminUser);
    }

}
