spring:
  application:
    name: TeaHub

  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  servlet:
    multipart:
      file-size-threshold: 10MB

  jpa:
    hibernate:
      ddl-auto: update


  cache:
    cache-names:
      - global-rate-limit
      - auth-rate-limit
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} | %highlight(%-5level) | %logger{0} | %msg%n"
  level:
    dev.parhamziaei: trace
  threshold:
    console: TRACE
  file:
    path: logs
    name: logs/application.log

app:
  settings:
    backend-domain: 'api.teacloud.ir'
  components:
    telnet:
      default-timeout-millis: 10000
      reconnect-tries: 10
      reconnect-delay: 60s

  service:
    payment:
      payment-success-redirect-uri: 'https://teacloud.ir/panel/invoices/{invoice_id}?result=true'
      payment-failed-redirect-uri: 'https://teacloud.ir/panel/invoices/{invoice_id}?result=false'
    media-storage:
      allowed-media-extension:
        - jpg
        - png
        - webp
      allowed-media-mime-type:
        - image/png
        - image/jpeg
        - image/webp
      maximum-media-size-mb: 10
      ticket-attachments-path: /home/arthur/spring-boot/uploads/ticket-attachments

    ticket:
      max-attachment-per-message: 5

  initialize:
    admin-email: javadtoktamp@gmail.com
    admin-phone-number: "9053781183"
    admin-first-name: parham
    admin-last-name: ziaei

  integration:
    teaspeak-query:
      port-step: 5
    ip-panel:
      base-url: https://edge.ippanel.com/v1
      api-key: YTI3NmRmNGQtY2ZhOS00MDVlLThhNWUtMWNiYzBhNzEzYmVkZjA0Y2ExNjExNDc5OTk0N2I2YjcyNTI1M2MzMGY0YTc=
      # Service will send one variable to IPPanel : (%code%) make sure you created this variable in patterns setting
      two-facto-message-pattern-code: llz1a8fbcs6n7hd
      from-number: 3000505

  cookie-factory:
    secure-cookie: false #TODO make this true in production
    two-factor-cookie-ttl: 300s
    phone-verify-cookie-ttl: 300s
    same-site-attribute: "Strict"
    domain: "teacloud.ir"

  jason-web-token:
    base64-secret: f633915d212d5159e506d6d69f6d1adcad3aff7396b05545df48183e1331d537 #Change this value on production phase, this is the whole authentication layer key , keep it secret ;)
    access-token-ttl: 1800s
    phone-verify-token-ttl: 300s
    refresh-token-ttl: 86400s
    two-factor-token-ttl: 180s

  sessions:
    phone-verify-session-ttl: 300s
    two-factor-session-ttl: 180s

springdoc:
  api-docs:
    enabled: true
    path: /docs

server:
  forward-headers-strategy: framework

bucket4j:
  enabled: true

  filters:
    # Auth endpoints
    - cache-name: auth-rate-limit
      filter-order: -101
      url: ^(/v1/auth/).*
      strategy: first
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
              refill-speed: interval

    # Global
    - cache-name: global-rate-limit
      filter-order: -100
      url: ^(/v1/).*
      strategy: first
      rate-limits:
        - bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
              refill-speed: interval