services:
#  backend:
#    build: .
#    container_name: spring-backend
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      DB_HOST: mysql:3306
#      DB_NAME: teahub
#      DB_USERNAME: admin
#      DB_PASSWORD: StrongPassword123!@#
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      KAFKA_BOOTSTRAP: kafka:9092
#    depends_on:
#      - mysql
#      - redis
#      - kafka
#    volumes:
#      - ./uploads:/app/uploads
#      - ./config:/app/config
#    networks:
#      - backend-net

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: StrongPassword123!@#
      MYSQL_DATABASE: teahub
      MYSQL_USER: admin
      MYSQL_PASSWORD: StrongPassword123!@#
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
    ports:
      - "8081:80"
    networks:
      - backend-net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-net

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    networks:
      - backend-net


volumes:
  mysql_data:
  redis_data:

networks:
  backend-net:

